// This file is auto-generated by @hey-api/openapi-ts

export { deleteAudio, getAudio, listAudio, type Options, updateAudio, uploadAudio } from './sdk.gen';
export type { AudioDeleted, AudioFile, AudioRenamed, ClientOptions, DeleteAudioData, DeleteAudioError, DeleteAudioErrors, DeleteAudioResponse, DeleteAudioResponses, Error, GetAudioData, GetAudioError, GetAudioErrors, GetAudioResponse, GetAudioResponses, ListAudioData, ListAudioError, ListAudioErrors, ListAudioResponse, ListAudioResponses, UpdateAudioData, UpdateAudioError, UpdateAudioErrors, UpdateAudioResponse, UpdateAudioResponses, UploadAudioData, UploadAudioError, UploadAudioErrors, UploadAudioResponse, UploadAudioResponses } from './types.gen';
