// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAudioData, DeleteAudioErrors, DeleteAudioResponses, GetAudioData, GetAudioErrors, GetAudioResponses, ListAudioData, ListAudioErrors, ListAudioResponses, UpdateAudioData, UpdateAudioErrors, UpdateAudioResponses, UploadAudioData, UploadAudioErrors, UploadAudioResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all audio files with duration
 */
export const listAudio = <ThrowOnError extends boolean = false>(options?: Options<ListAudioData, ThrowOnError>) => (options?.client ?? client).get<ListAudioResponses, ListAudioErrors, ThrowOnError>({ url: '/audio', ...options });

/**
 * Upload a new audio file
 */
export const uploadAudio = <ThrowOnError extends boolean = false>(options: Options<UploadAudioData, ThrowOnError>) => (options.client ?? client).post<UploadAudioResponses, UploadAudioErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/audio',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete an audio file
 */
export const deleteAudio = <ThrowOnError extends boolean = false>(options: Options<DeleteAudioData, ThrowOnError>) => (options.client ?? client).delete<DeleteAudioResponses, DeleteAudioErrors, ThrowOnError>({ url: '/audio/{name}', ...options });

/**
 * Get audio file by name
 */
export const getAudio = <ThrowOnError extends boolean = false>(options: Options<GetAudioData, ThrowOnError>) => (options.client ?? client).get<GetAudioResponses, GetAudioErrors, ThrowOnError>({ url: '/audio/{name}', ...options });

/**
 * Rename audio file
 */
export const updateAudio = <ThrowOnError extends boolean = false>(options: Options<UpdateAudioData, ThrowOnError>) => (options.client ?? client).patch<UpdateAudioResponses, UpdateAudioErrors, ThrowOnError>({
    url: '/audio/{name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
