// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3008' | (string & {});
};

export type AudioFile = {
    /**
     * Audio filename
     */
    name: string;
    /**
     * Duration in milliseconds
     */
    durationMs: number;
};

export type AudioRenamed = {
    /**
     * New audio filename
     */
    name: string;
};

export type AudioDeleted = {
    /**
     * Name of the deleted audio file
     */
    deleted: string;
};

export type Error = {
    /**
     * Error message
     */
    error: string;
};

export type ListAudioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/audio';
};

export type ListAudioErrors = {
    /**
     * Server error
     */
    500: Error;
};

export type ListAudioError = ListAudioErrors[keyof ListAudioErrors];

export type ListAudioResponses = {
    /**
     * Array of audio file metadata
     */
    200: Array<AudioFile>;
};

export type ListAudioResponse = ListAudioResponses[keyof ListAudioResponses];

export type UploadAudioData = {
    body: {
        audio: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/audio';
};

export type UploadAudioErrors = {
    /**
     * No audio provided
     */
    400: Error;
};

export type UploadAudioError = UploadAudioErrors[keyof UploadAudioErrors];

export type UploadAudioResponses = {
    /**
     * Audio uploaded successfully
     */
    201: AudioFile;
};

export type UploadAudioResponse = UploadAudioResponses[keyof UploadAudioResponses];

export type DeleteAudioData = {
    body?: never;
    path: {
        /**
         * Audio filename
         */
        name: string;
    };
    query?: never;
    url: '/audio/{name}';
};

export type DeleteAudioErrors = {
    /**
     * Audio not found
     */
    404: Error;
};

export type DeleteAudioError = DeleteAudioErrors[keyof DeleteAudioErrors];

export type DeleteAudioResponses = {
    /**
     * Audio deleted
     */
    200: AudioDeleted;
};

export type DeleteAudioResponse = DeleteAudioResponses[keyof DeleteAudioResponses];

export type GetAudioData = {
    body?: never;
    path: {
        /**
         * Audio filename
         */
        name: string;
    };
    query?: never;
    url: '/audio/{name}';
};

export type GetAudioErrors = {
    /**
     * Audio not found
     */
    404: Error;
};

export type GetAudioError = GetAudioErrors[keyof GetAudioErrors];

export type GetAudioResponses = {
    /**
     * The audio file
     */
    200: Blob | File;
};

export type GetAudioResponse = GetAudioResponses[keyof GetAudioResponses];

export type UpdateAudioData = {
    body?: {
        /**
         * New filename for the audio
         */
        newName?: string;
    };
    path: {
        /**
         * Audio filename
         */
        name: string;
    };
    query?: never;
    url: '/audio/{name}';
};

export type UpdateAudioErrors = {
    /**
     * No newName provided
     */
    400: Error;
    /**
     * Audio not found
     */
    404: Error;
    /**
     * Target name already exists
     */
    409: Error;
};

export type UpdateAudioError = UpdateAudioErrors[keyof UpdateAudioErrors];

export type UpdateAudioResponses = {
    /**
     * Audio renamed
     */
    200: AudioRenamed;
};

export type UpdateAudioResponse = UpdateAudioResponses[keyof UpdateAudioResponses];
