// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateOutlineData, GenerateOutlineResponses, GenerateSceneTextData, GenerateSceneTextResponses, GenerateStoryMasterPromptData, GenerateStoryMasterPromptResponses, GetBatchStatusData, GetBatchStatusErrors, GetBatchStatusResponses, ListBatchesData, ListBatchesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate a story master prompt (backbone) for a visual novel
 */
export const generateStoryMasterPrompt = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryMasterPromptData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryMasterPromptResponses, unknown, ThrowOnError>({
    url: '/generate/storyMasterPrompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate scene text and outputs for a visual novel scene
 */
export const generateSceneText = <ThrowOnError extends boolean = false>(options: Options<GenerateSceneTextData, ThrowOnError>) => (options.client ?? client).post<GenerateSceneTextResponses, unknown, ThrowOnError>({
    url: '/generate/sceneText',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a high-level outline (acts + anchor skeleton) from a brief
 */
export const generateOutline = <ThrowOnError extends boolean = false>(options: Options<GenerateOutlineData, ThrowOnError>) => (options.client ?? client).post<GenerateOutlineResponses, unknown, ThrowOnError>({
    url: '/generate/outline',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all batches with summary stats
 */
export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>) => (options?.client ?? client).get<ListBatchesResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * Get detailed status of a batch
 */
export const getBatchStatus = <ThrowOnError extends boolean = false>(options: Options<GetBatchStatusData, ThrowOnError>) => (options.client ?? client).get<GetBatchStatusResponses, GetBatchStatusErrors, ThrowOnError>({ url: '/status/{batchId}', ...options });
