// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateAnchorBeatData, GenerateAnchorBeatResponses, GenerateBeatPlanData, GenerateBeatPlanResponses, GenerateDialogueVariantData, GenerateDialogueVariantResponses, GenerateEndingData, GenerateEndingResponses, GenerateLiCardsData, GenerateLiCardsResponses, GenerateNarrationWebData, GenerateNarrationWebResponses, GenerateOutlineData, GenerateOutlineResponses, GenerateSceneTextData, GenerateSceneTextResponses, GenerateSegmentData, GenerateSegmentResponses, GenerateStoryMasterPromptData, GenerateStoryMasterPromptResponses, GenerateWorldModelData, GenerateWorldModelResponses, GetBatchStatusData, GetBatchStatusErrors, GetBatchStatusResponses, ListBatchesData, ListBatchesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate a story master prompt (backbone) for a visual novel
 */
export const generateStoryMasterPrompt = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryMasterPromptData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryMasterPromptResponses, unknown, ThrowOnError>({
    url: '/generate/storyMasterPrompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate scene text and outputs for a visual novel scene
 */
export const generateSceneText = <ThrowOnError extends boolean = false>(options: Options<GenerateSceneTextData, ThrowOnError>) => (options.client ?? client).post<GenerateSceneTextResponses, unknown, ThrowOnError>({
    url: '/generate/sceneText',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a high-level outline (acts + anchor skeleton) from a brief
 */
export const generateOutline = <ThrowOnError extends boolean = false>(options: Options<GenerateOutlineData, ThrowOnError>) => (options.client ?? client).post<GenerateOutlineResponses, unknown, ThrowOnError>({
    url: '/generate/outline',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate scene-level draft DAG between two outline anchors
 */
export const generateSegment = <ThrowOnError extends boolean = false>(options: Options<GenerateSegmentData, ThrowOnError>) => (options.client ?? client).post<GenerateSegmentResponses, unknown, ThrowOnError>({
    url: '/generate/segment',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate love interest character cards from a story master prompt
 */
export const generateLiCards = <ThrowOnError extends boolean = false>(options: Options<GenerateLiCardsData, ThrowOnError>) => (options.client ?? client).post<GenerateLiCardsResponses, unknown, ThrowOnError>({
    url: '/generate/liCards',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a narration web (exploration DAG) between two story anchors
 */
export const generateNarrationWeb = <ThrowOnError extends boolean = false>(options: Options<GenerateNarrationWebData, ThrowOnError>) => (options.client ?? client).post<GenerateNarrationWebResponses, unknown, ThrowOnError>({
    url: '/generate/narrationWeb',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Build the persistent world model (locations registry with adjacency) from the outline
 */
export const generateWorldModel = <ThrowOnError extends boolean = false>(options: Options<GenerateWorldModelData, ThrowOnError>) => (options.client ?? client).post<GenerateWorldModelResponses, unknown, ThrowOnError>({
    url: '/generate/worldModel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Plan relationship beats across encounter slots of the story outline
 */
export const generateBeatPlan = <ThrowOnError extends boolean = false>(options: Options<GenerateBeatPlanData, ThrowOnError>) => (options.client ?? client).post<GenerateBeatPlanResponses, unknown, ThrowOnError>({
    url: '/generate/beatPlan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate an on-screen beat scene for a story anchor with diegetic transition labels
 */
export const generateAnchorBeat = <ThrowOnError extends boolean = false>(options: Options<GenerateAnchorBeatData, ThrowOnError>) => (options.client ?? client).post<GenerateAnchorBeatResponses, unknown, ThrowOnError>({
    url: '/generate/anchorBeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate an epilogue variant (good per-LI, or shared normal/bad)
 */
export const generateEnding = <ThrowOnError extends boolean = false>(options: Options<GenerateEndingData, ThrowOnError>) => (options.client ?? client).post<GenerateEndingResponses, unknown, ThrowOnError>({
    url: '/generate/ending',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a dialogue variant for a character encounter at a given relationship bracket
 */
export const generateDialogueVariant = <ThrowOnError extends boolean = false>(options: Options<GenerateDialogueVariantData, ThrowOnError>) => (options.client ?? client).post<GenerateDialogueVariantResponses, unknown, ThrowOnError>({
    url: '/generate/dialogueVariant',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all batches with summary stats
 */
export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>) => (options?.client ?? client).get<ListBatchesResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * Get detailed status of a batch
 */
export const getBatchStatus = <ThrowOnError extends boolean = false>(options: Options<GetBatchStatusData, ThrowOnError>) => (options.client ?? client).get<GetBatchStatusResponses, GetBatchStatusErrors, ThrowOnError>({ url: '/status/{batchId}', ...options });
