// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateAnchorBeatData, GenerateAnchorBeatResponses, GenerateAnchorTransitionData, GenerateAnchorTransitionResponses, GenerateCastPlanData, GenerateCastPlanResponses, GenerateDialogueQaData, GenerateDialogueQaResponses, GenerateDialogueUnitData, GenerateDialogueUnitResponses, GenerateEndingData, GenerateEndingResponses, GenerateEventPoolData, GenerateEventPoolResponses, GenerateSceneTextData, GenerateSceneTextResponses, GenerateSpineData, GenerateSpineResponses, GenerateStoryLeafQaData, GenerateStoryLeafQaResponses, GenerateStoryMasterPromptData, GenerateStoryMasterPromptResponses, GenerateWorldCalendarData, GenerateWorldCalendarResponses, GetBatchStatusData, GetBatchStatusErrors, GetBatchStatusResponses, ListBatchesData, ListBatchesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate a story master prompt (backbone) for a visual novel
 */
export const generateStoryMasterPrompt = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryMasterPromptData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryMasterPromptResponses, unknown, ThrowOnError>({
    url: '/generate/storyMasterPrompt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate scene text and outputs for a visual novel scene
 */
export const generateSceneText = <ThrowOnError extends boolean = false>(options: Options<GenerateSceneTextData, ThrowOnError>) => (options.client ?? client).post<GenerateSceneTextResponses, unknown, ThrowOnError>({
    url: '/generate/sceneText',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Build world locations, the discrete story calendar and the agenda-tag-to-location map
 */
export const generateWorldCalendar = <ThrowOnError extends boolean = false>(options: Options<GenerateWorldCalendarData, ThrowOnError>) => (options.client ?? client).post<GenerateWorldCalendarResponses, unknown, ThrowOnError>({
    url: '/generate/worldCalendar',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate the cast plan (per-LI agendas with arc-stage goals and weekly location-tag patterns)
 */
export const generateCastPlan = <ThrowOnError extends boolean = false>(options: Options<GenerateCastPlanData, ThrowOnError>) => (options.client ?? client).post<GenerateCastPlanResponses, unknown, ThrowOnError>({
    url: '/generate/castPlan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a per-character event pool (storylet shells with guards, goals and effects, no prose)
 */
export const generateEventPool = <ThrowOnError extends boolean = false>(options: Options<GenerateEventPoolData, ThrowOnError>) => (options.client ?? client).post<GenerateEventPoolResponses, unknown, ThrowOnError>({
    url: '/generate/eventPool',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate the story spine (beats with slot windows and guarded endings) over world and calendar
 */
export const generateSpine = <ThrowOnError extends boolean = false>(options: Options<GenerateSpineData, ThrowOnError>) => (options.client ?? client).post<GenerateSpineResponses, unknown, ThrowOnError>({
    url: '/generate/spine',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate an on-screen beat scene for a story anchor with diegetic transition labels
 */
export const generateAnchorBeat = <ThrowOnError extends boolean = false>(options: Options<GenerateAnchorBeatData, ThrowOnError>) => (options.client ?? client).post<GenerateAnchorBeatResponses, unknown, ThrowOnError>({
    url: '/generate/anchorBeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate diegetic daypart-transition scenes (go to class, go to sleep)
 */
export const generateAnchorTransition = <ThrowOnError extends boolean = false>(options: Options<GenerateAnchorTransitionData, ThrowOnError>) => (options.client ?? client).post<GenerateAnchorTransitionResponses, unknown, ThrowOnError>({
    url: '/generate/anchorTransition',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate an epilogue variant (good per-LI, or shared normal/bad)
 */
export const generateEnding = <ThrowOnError extends boolean = false>(options: Options<GenerateEndingData, ThrowOnError>) => (options.client ?? client).post<GenerateEndingResponses, unknown, ThrowOnError>({
    url: '/generate/ending',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a first-class dialogue unit (typed choices, closing nodes) for a character encounter at a given relationship bracket
 */
export const generateDialogueUnit = <ThrowOnError extends boolean = false>(options: Options<GenerateDialogueUnitData, ThrowOnError>) => (options.client ?? client).post<GenerateDialogueUnitResponses, unknown, ThrowOnError>({
    url: '/generate/dialogueUnit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * LLM-critic pass over a generated dialogue unit (answers, tone, closing completeness)
 */
export const generateDialogueQa = <ThrowOnError extends boolean = false>(options: Options<GenerateDialogueQaData, ThrowOnError>) => (options.client ?? client).post<GenerateDialogueQaResponses, unknown, ThrowOnError>({
    url: '/generate/dialogueQA',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * LLM-critic pass over one branch leaf of the story (beat contradictions, knowledge continuity, finale consistency)
 */
export const generateStoryLeafQa = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryLeafQaData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryLeafQaResponses, unknown, ThrowOnError>({
    url: '/generate/storyLeafQA',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all batches with summary stats
 */
export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>) => (options?.client ?? client).get<ListBatchesResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * Get detailed status of a batch
 */
export const getBatchStatus = <ThrowOnError extends boolean = false>(options: Options<GetBatchStatusData, ThrowOnError>) => (options.client ?? client).get<GetBatchStatusResponses, GetBatchStatusErrors, ThrowOnError>({ url: '/status/{batchId}', ...options });
