// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3200' | (string & {});
};

export type StoryMasterPromptRequest = {
    /**
     * Optional author wishes / theme hint for the story generation
     */
    userHint?: string;
};

export type GenerateResponse = {
    batchId: string;
    itemIds: Array<string>;
};

export type CompletedTextItem = {
    id: string;
    /**
     * Generated text content
     */
    result?: string;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<CompletedTextItem>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: number;
    pending: number;
    failed: number;
};

export type SceneChainItem = {
    /**
     * Text of a previous scene
     */
    sceneText: string;
    /**
     * The choice/output text that led from this scene to the next
     */
    outputText: string;
};

export type SceneCharacter = {
    /**
     * Character name
     */
    name: string;
    /**
     * Character description (appearance, personality, role)
     */
    description?: string;
};

export type SceneTextRequest = {
    /**
     * The story master prompt (backbone of the story)
     */
    storyMasterPrompt: string;
    /**
     * Chain of previous scenes leading to this one
     */
    sceneChain: Array<SceneChainItem>;
    /**
     * Depth of this scene from the root (0-based)
     */
    depth: number;
    /**
     * Estimated maximum depth of the story tree
     */
    maxDepth: number;
    /**
     * The output/choice text that leads into this scene
     */
    incomingOutputText: string;
    /**
     * Characters present in this scene
     */
    characters?: Array<SceneCharacter>;
};

export type OutlineRequest = {
    /**
     * Procedural narrative brief (Brief in client/src/narrative/types.ts).
     * Treated as opaque JSON by text_gen — embedded into the prompt as-is.
     *
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * Map of archetypeId -> ArchetypeProfile, only the archetypes
     * referenced by the brief's loveInterests. Embedded into the prompt
     * so the LLM knows which beats are required per route.
     *
     */
    archetypeProfiles: {
        [key: string]: unknown;
    };
};

export type SegmentRequest = {
    /**
     * Brief context (characters, world, tone, art style, scale).
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * ArchetypeProfile of the LI on this route, or null for common-route
     * segments. Used by the LLM to apply trajectory rules and beat themes.
     *
     */
    archetypeProfile?: {
        [key: string]: unknown;
    };
    /**
     * AnchorPlan of the source anchor (segment entry).
     */
    anchorFrom: {
        [key: string]: unknown;
    };
    /**
     * AnchorPlan of the target anchor (segment exit). Its
     * entryStateRequired ranges/flags define the success criterion.
     *
     */
    anchorTo: {
        [key: string]: unknown;
    };
    /**
     * Flags already established by ancestors of anchorFrom in the outline.
     * Helps the LLM stay consistent with what has already happened.
     *
     */
    existingFlags?: Array<string>;
};

export type ErrorResponse = {
    error: string;
};

export type GenerateStoryMasterPromptData = {
    body: StoryMasterPromptRequest;
    path?: never;
    query?: never;
    url: '/generate/storyMasterPrompt';
};

export type GenerateStoryMasterPromptResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateStoryMasterPromptResponse = GenerateStoryMasterPromptResponses[keyof GenerateStoryMasterPromptResponses];

export type GenerateSceneTextData = {
    body: SceneTextRequest;
    path?: never;
    query?: never;
    url: '/generate/sceneText';
};

export type GenerateSceneTextResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateSceneTextResponse = GenerateSceneTextResponses[keyof GenerateSceneTextResponses];

export type GenerateOutlineData = {
    body: OutlineRequest;
    path?: never;
    query?: never;
    url: '/generate/outline';
};

export type GenerateOutlineResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateOutlineResponse = GenerateOutlineResponses[keyof GenerateOutlineResponses];

export type GenerateSegmentData = {
    body: SegmentRequest;
    path?: never;
    query?: never;
    url: '/generate/segment';
};

export type GenerateSegmentResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateSegmentResponse = GenerateSegmentResponses[keyof GenerateSegmentResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListBatchesResponses = {
    /**
     * List of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchStatusData = {
    body?: never;
    path: {
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: ErrorResponse;
};

export type GetBatchStatusError = GetBatchStatusErrors[keyof GetBatchStatusErrors];

export type GetBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetBatchStatusResponse = GetBatchStatusResponses[keyof GetBatchStatusResponses];
