// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3200' | (string & {});
};

export type StoryMasterPromptRequest = {
    /**
     * Optional author wishes / theme hint for the story generation
     */
    userHint?: string;
};

export type GenerateResponse = {
    batchId: string;
    itemIds: Array<string>;
};

export type CompletedTextItem = {
    id: string;
    /**
     * Generated text content
     */
    result?: string;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<CompletedTextItem>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: number;
    pending: number;
    failed: number;
};

export type ErrorResponse = {
    error: string;
};

export type GenerateStoryMasterPromptData = {
    body: StoryMasterPromptRequest;
    path?: never;
    query?: never;
    url: '/generate/storyMasterPrompt';
};

export type GenerateStoryMasterPromptResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateStoryMasterPromptResponse = GenerateStoryMasterPromptResponses[keyof GenerateStoryMasterPromptResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListBatchesResponses = {
    /**
     * List of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchStatusData = {
    body?: never;
    path: {
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: ErrorResponse;
};

export type GetBatchStatusError = GetBatchStatusErrors[keyof GetBatchStatusErrors];

export type GetBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetBatchStatusResponse = GetBatchStatusResponses[keyof GetBatchStatusResponses];
