// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3200' | (string & {});
};

export type StoryMasterPromptRequest = {
    /**
     * Optional author wishes / theme hint for the story generation
     */
    userHint?: string;
};

export type GenerateResponse = {
    batchId: string;
    itemIds: Array<string>;
};

export type CompletedTextItem = {
    id: string;
    /**
     * Generated text content
     */
    result?: string;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<CompletedTextItem>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: number;
    pending: number;
    failed: number;
};

export type SceneChainItem = {
    /**
     * Text of a previous scene
     */
    sceneText: string;
    /**
     * The choice/output text that led from this scene to the next
     */
    outputText: string;
};

export type SceneCharacter = {
    /**
     * Character name
     */
    name: string;
    /**
     * Character description (appearance, personality, role)
     */
    description?: string;
};

export type SceneTextRequest = {
    /**
     * The story master prompt (backbone of the story)
     */
    storyMasterPrompt: string;
    /**
     * Chain of previous scenes leading to this one
     */
    sceneChain: Array<SceneChainItem>;
    /**
     * Depth of this scene from the root (0-based)
     */
    depth: number;
    /**
     * Estimated maximum depth of the story tree
     */
    maxDepth: number;
    /**
     * The output/choice text that leads into this scene
     */
    incomingOutputText: string;
    /**
     * Characters present in this scene
     */
    characters?: Array<SceneCharacter>;
};

export type OutlineRequest = {
    /**
     * Procedural narrative brief (Brief in client/src/narrative/types.ts).
     * Treated as opaque JSON by text_gen — embedded into the prompt as-is.
     *
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * Map of archetypeId -> ArchetypeProfile, only the archetypes
     * referenced by the brief's loveInterests. Embedded into the prompt
     * so the LLM knows which beats are required per route.
     *
     */
    archetypeProfiles: {
        [key: string]: unknown;
    };
    /**
     * Computed budgets: anchorCount, anchorsPerAct, plotOnlyAnchorCount
     * (derived from targetDurationMinutes / commonRouteShare).
     *
     */
    targets?: {
        [key: string]: unknown;
    };
    /**
     * Previously generated outline that failed validation. When present
     * alongside previousIssues, the LLM is asked to produce a corrected
     * version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type SegmentRequest = {
    /**
     * Brief context (characters, world, tone, art style, scale).
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * ArchetypeProfile of the LI on this route, or null for common-route
     * segments. Used by the LLM to apply trajectory rules and beat themes.
     *
     */
    archetypeProfile?: {
        [key: string]: unknown;
    };
    /**
     * AnchorPlan of the source anchor (segment entry).
     */
    anchorFrom: {
        [key: string]: unknown;
    };
    /**
     * AnchorPlan of the target anchor (segment exit). Its
     * entryStateRequired ranges/flags define the success criterion.
     *
     */
    anchorTo: {
        [key: string]: unknown;
    };
    /**
     * Flags already established by ancestors of anchorFrom in the outline.
     * Helps the LLM stay consistent with what has already happened.
     *
     */
    existingFlags?: Array<string>;
    /**
     * Baseline state ranges at segment entry: {[stateVarPath]: [lo, hi]}.
     * Computed on the client by reconciling anchorFrom.entryStateRequired
     * with archetype.initialState. Shown to the LLM verbatim in the prompt
     * and used by the validator's range-feasibility check — eliminates
     * hidden 0-default mismatches that previously caused infinite retry
     * loops.
     *
     */
    baselineStateRanges?: {
        [key: string]: [
            number,
            number
        ];
    };
    /**
     * Previously generated GeneratedSegment that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * regenerate with awareness of what failed before.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Human-readable list of issues from the previous attempt
     * (e.g. "ни один из 4 путей не приводит state в требования
     * anchorTo"). Each entry is shown to the LLM verbatim.
     *
     */
    previousIssues?: Array<string>;
};

export type LiCardsRequest = {
    /**
     * The story master prompt text describing the world and setting
     */
    storyMasterPrompt: string;
    /**
     * Number of love interest characters to generate
     */
    count: number;
    /**
     * Optional hints to guide LI generation
     */
    hints?: {
        /**
         * Preferred archetype IDs (slow_burn, enemies_to_lovers, etc.)
         */
        archetypes?: Array<string>;
        /**
         * Additional constraints for LI generation
         */
        constraints?: string;
    };
};

export type NarrationWebRequest = {
    /**
     * Brief context (world, tone, protagonist).
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * StoryAnchor of the source (segment entry).
     */
    storyAnchorFrom: {
        [key: string]: unknown;
    };
    /**
     * StoryAnchor of the target (segment exit).
     */
    storyAnchorTo: {
        [key: string]: unknown;
    };
    /**
     * Love interests available for encounter in this location.
     */
    availableLIs: Array<{
        liId: string;
        liName: string;
        roleInWorld: string;
    }>;
    /**
     * Flags already established by prior story anchors.
     */
    existingFlags?: Array<string>;
    /**
     * Beat scene text of the FROM anchor the player just saw; the web continues right after it.
     */
    fromAnchorBeatText?: string;
    /**
     * LI ids whose encounters are planned at this anchor; the web must contain a trigger for each.
     */
    plannedEncounterLIs?: Array<string>;
    /**
     * World-model location entity of the FROM anchor.
     */
    fromLocation?: {
        [key: string]: unknown;
    };
    /**
     * World-model location entity of the TO anchor.
     */
    toLocation?: {
        [key: string]: unknown;
    };
    /**
     * Ordered location path from -> to; web scenes must move forward along it.
     */
    route?: Array<{
        locationId: string;
        name: string;
        via: string;
    }>;
    /**
     * Previously generated NarrationWeb that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * produce a corrected version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type WorldModelRequest = {
    brief: {
        [key: string]: unknown;
    };
    /**
     * StoryOutlinePlan with anchors (free-text locations) and edges.
     */
    outline: {
        [key: string]: unknown;
    };
    /**
     * Previously generated world model that failed validation.
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type WorldCalendarRequest = {
    /**
     * Procedural narrative brief, embedded into the prompt as-is.
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * CastPlan with per-LI agenda location tags (workplace/hangout/home...);
     * every tag must be mapped to at least one location. Null when agendas
     * are stubbed client-side.
     *
     */
    castPlan?: {
        [key: string]: unknown;
    };
    /**
     * Calendar sizes computed from brief.scale (computeCalendarTargets):
     * the generated calendar must match them exactly.
     *
     */
    targets: {
        days: number;
        daypartsPerDay: number;
        slotCount: number;
        acts: number;
    };
    /**
     * Previously generated world+calendar that failed validation.
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type SpineRequest = {
    brief: {
        [key: string]: unknown;
    };
    /**
     * World model (locations registry) the beats reference by id.
     */
    worldModel: {
        [key: string]: unknown;
    };
    /**
     * Discrete calendar (days, dayparts, actBoundaries).
     */
    calendar: {
        [key: string]: unknown;
    };
    /**
     * Agenda-tag to location-ids mapping, or null.
     */
    tagMap?: {
        [key: string]: unknown;
    };
    /**
     * Budgets: number of beats (±1) and branch point limit
     * (0 in the current format version — branchPoint kind forbidden).
     *
     */
    targets: {
        beatCount: number;
        branchPointBudget: number;
    };
    /**
     * Previously generated spine that failed validation.
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type BeatPlanRequest = {
    /**
     * Brief context (world, tone, LI cast).
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * StoryOutlinePlan with anchors pre-sorted topologically.
     */
    outline: {
        [key: string]: unknown;
    };
    /**
     * Archetype profiles keyed by archetype id (requiredBeats source).
     */
    archetypeProfiles: {
        [key: string]: unknown;
    };
    /**
     * Allowed (anchor x LI) encounter slots.
     */
    encounterSlots: Array<{
        anchorId: string;
        act: number;
        location: string;
        liIds: Array<string>;
    }>;
    /**
     * Previously generated BeatPlan that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * produce a corrected version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type AnchorBeatRequest = {
    /**
     * Brief context (world, tone, protagonist).
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * StoryAnchor whose event this beat scene plays on screen.
     */
    anchor: {
        [key: string]: unknown;
    };
    /**
     * Purpose of the act this anchor belongs to (outline.acts[act-1].purpose).
     */
    actPurpose: string;
    /**
     * Ancestor beat chain in topological order (last 4).
     */
    predecessorBeats: Array<{
        anchorId: string;
        summary: string;
        beatText?: string;
    }>;
    /**
     * Outgoing anchor targets requiring diegetic transition labels.
     */
    outgoingTargets: Array<{
        anchorId: string;
        summary: string;
        location: string;
        timeMarker: string;
    }>;
    /**
     * World-model location entity of this anchor.
     */
    location?: {
        [key: string]: unknown;
    };
    /**
     * How the player physically arrives (via of the route's last leg).
     */
    arrivedVia?: string;
    /**
     * Previously generated AnchorBeat that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * produce a corrected version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type EndingRequest = {
    brief: {
        [key: string]: unknown;
    };
    /**
     * Title, logline, acts and the resolution anchor.
     */
    outline: {
        [key: string]: unknown;
    };
    kind: 'good' | 'normal' | 'bad';
    /**
     * LI card, only for kind=good.
     */
    liCard?: {
        [key: string]: unknown;
    };
    /**
     * Tone from archetype.endingProfile[kind].tone.
     */
    endingTone?: string;
    liArcSummary?: string;
    finalEncounterGoal?: string;
    resolutionBeatText?: string;
    /**
     * Previously generated ending that failed validation.
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type DialogueVariantRequest = {
    /**
     * Brief context.
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * Full LoveInterestCard of the character.
     */
    liCard: {
        [key: string]: unknown;
    };
    /**
     * ArchetypeProfile for the character's archetype.
     */
    archetypeProfile: {
        [key: string]: unknown;
    };
    /**
     * Current story context (where/when the encounter happens).
     */
    storyContext: {
        location: string;
        timeMarker: string;
        recentEvents: string;
    };
    /**
     * Relationship bracket determining dialogue tone.
     */
    bracket: 'positive' | 'neutral' | 'negative';
    /**
     * Expected relationship state ranges at encounter entry.
     */
    stateRanges: {
        [key: string]: [
            number,
            number
        ];
    };
    /**
     * Arc context from the beat plan: encounter index/total, target
     * beat, per-encounter goal, prior encounter goals, anchor beat text.
     *
     */
    encounterContext?: {
        [key: string]: unknown;
    };
    /**
     * Previously generated DialogueVariant that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * produce a corrected version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type DialogueUnitRequest = {
    /**
     * Brief context.
     */
    brief: {
        [key: string]: unknown;
    };
    /**
     * Full LoveInterestCard of the character.
     */
    liCard: {
        [key: string]: unknown;
    };
    /**
     * ArchetypeProfile for the character's archetype.
     */
    archetypeProfile: {
        [key: string]: unknown;
    };
    /**
     * Current story context (where/when the encounter happens).
     */
    storyContext: {
        location: string;
        timeMarker: string;
        recentEvents: string;
    };
    /**
     * Relationship bracket determining dialogue tone.
     */
    bracket: 'positive' | 'neutral' | 'negative';
    /**
     * Expected relationship state ranges at encounter entry.
     */
    stateRanges: {
        [key: string]: [
            number,
            number
        ];
    };
    /**
     * Arc context from the beat plan: encounter index/total, target
     * beat, per-encounter goal, prior encounter goals, anchor beat text.
     *
     */
    encounterContext?: {
        [key: string]: unknown;
    };
    /**
     * Previously generated DialogueUnit that failed validation.
     * When present alongside previousIssues, the LLM is asked to
     * produce a corrected version.
     *
     */
    previousAttempt?: {
        [key: string]: unknown;
    };
    /**
     * Validation issue messages from the previous attempt.
     */
    previousIssues?: Array<string>;
};

export type DialogueQaRequest = {
    /**
     * The generated DialogueUnit to review (opaque JSON).
     */
    unit: {
        [key: string]: unknown;
    };
    /**
     * Relationship bracket the unit was generated for.
     */
    bracket: 'positive' | 'neutral' | 'negative';
    /**
     * Short summary of the LI card (name, personality, speech style).
     */
    liCardSummary: string;
};

export type ErrorResponse = {
    error: string;
};

export type GenerateStoryMasterPromptData = {
    body: StoryMasterPromptRequest;
    path?: never;
    query?: never;
    url: '/generate/storyMasterPrompt';
};

export type GenerateStoryMasterPromptResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateStoryMasterPromptResponse = GenerateStoryMasterPromptResponses[keyof GenerateStoryMasterPromptResponses];

export type GenerateSceneTextData = {
    body: SceneTextRequest;
    path?: never;
    query?: never;
    url: '/generate/sceneText';
};

export type GenerateSceneTextResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateSceneTextResponse = GenerateSceneTextResponses[keyof GenerateSceneTextResponses];

export type GenerateOutlineData = {
    body: OutlineRequest;
    path?: never;
    query?: never;
    url: '/generate/outline';
};

export type GenerateOutlineResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateOutlineResponse = GenerateOutlineResponses[keyof GenerateOutlineResponses];

export type GenerateSegmentData = {
    body: SegmentRequest;
    path?: never;
    query?: never;
    url: '/generate/segment';
};

export type GenerateSegmentResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateSegmentResponse = GenerateSegmentResponses[keyof GenerateSegmentResponses];

export type GenerateLiCardsData = {
    body: LiCardsRequest;
    path?: never;
    query?: never;
    url: '/generate/liCards';
};

export type GenerateLiCardsResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateLiCardsResponse = GenerateLiCardsResponses[keyof GenerateLiCardsResponses];

export type GenerateNarrationWebData = {
    body: NarrationWebRequest;
    path?: never;
    query?: never;
    url: '/generate/narrationWeb';
};

export type GenerateNarrationWebResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateNarrationWebResponse = GenerateNarrationWebResponses[keyof GenerateNarrationWebResponses];

export type GenerateWorldModelData = {
    body: WorldModelRequest;
    path?: never;
    query?: never;
    url: '/generate/worldModel';
};

export type GenerateWorldModelResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateWorldModelResponse = GenerateWorldModelResponses[keyof GenerateWorldModelResponses];

export type GenerateWorldCalendarData = {
    body: WorldCalendarRequest;
    path?: never;
    query?: never;
    url: '/generate/worldCalendar';
};

export type GenerateWorldCalendarResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateWorldCalendarResponse = GenerateWorldCalendarResponses[keyof GenerateWorldCalendarResponses];

export type GenerateSpineData = {
    body: SpineRequest;
    path?: never;
    query?: never;
    url: '/generate/spine';
};

export type GenerateSpineResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateSpineResponse = GenerateSpineResponses[keyof GenerateSpineResponses];

export type GenerateBeatPlanData = {
    body: BeatPlanRequest;
    path?: never;
    query?: never;
    url: '/generate/beatPlan';
};

export type GenerateBeatPlanResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateBeatPlanResponse = GenerateBeatPlanResponses[keyof GenerateBeatPlanResponses];

export type GenerateAnchorBeatData = {
    body: AnchorBeatRequest;
    path?: never;
    query?: never;
    url: '/generate/anchorBeat';
};

export type GenerateAnchorBeatResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateAnchorBeatResponse = GenerateAnchorBeatResponses[keyof GenerateAnchorBeatResponses];

export type GenerateEndingData = {
    body: EndingRequest;
    path?: never;
    query?: never;
    url: '/generate/ending';
};

export type GenerateEndingResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateEndingResponse = GenerateEndingResponses[keyof GenerateEndingResponses];

export type GenerateDialogueVariantData = {
    body: DialogueVariantRequest;
    path?: never;
    query?: never;
    url: '/generate/dialogueVariant';
};

export type GenerateDialogueVariantResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateDialogueVariantResponse = GenerateDialogueVariantResponses[keyof GenerateDialogueVariantResponses];

export type GenerateDialogueUnitData = {
    body: DialogueUnitRequest;
    path?: never;
    query?: never;
    url: '/generate/dialogueUnit';
};

export type GenerateDialogueUnitResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateDialogueUnitResponse = GenerateDialogueUnitResponses[keyof GenerateDialogueUnitResponses];

export type GenerateDialogueQaData = {
    body: DialogueQaRequest;
    path?: never;
    query?: never;
    url: '/generate/dialogueQA';
};

export type GenerateDialogueQaResponses = {
    /**
     * Generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateDialogueQaResponse = GenerateDialogueQaResponses[keyof GenerateDialogueQaResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListBatchesResponses = {
    /**
     * List of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchStatusData = {
    body?: never;
    path: {
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: ErrorResponse;
};

export type GetBatchStatusError = GetBatchStatusErrors[keyof GetBatchStatusErrors];

export type GetBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetBatchStatusResponse = GetBatchStatusResponses[keyof GetBatchStatusResponses];
