// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteImageData, DeleteImageErrors, DeleteImageResponses, GetImageData, GetImageErrors, GetImageResponses, GetImageThumbnailData, GetImageThumbnailErrors, GetImageThumbnailResponses, ListImagesData, ListImagesErrors, ListImagesResponses, UpdateImageData, UpdateImageErrors, UpdateImageResponses, UploadImageData, UploadImageErrors, UploadImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all image names
 */
export const listImages = <ThrowOnError extends boolean = false>(options?: Options<ListImagesData, ThrowOnError>) => (options?.client ?? client).get<ListImagesResponses, ListImagesErrors, ThrowOnError>({ url: '/images', ...options });

/**
 * Upload a new image
 */
export const uploadImage = <ThrowOnError extends boolean = false>(options: Options<UploadImageData, ThrowOnError>) => (options.client ?? client).post<UploadImageResponses, UploadImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/images',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete an image
 */
export const deleteImage = <ThrowOnError extends boolean = false>(options: Options<DeleteImageData, ThrowOnError>) => (options.client ?? client).delete<DeleteImageResponses, DeleteImageErrors, ThrowOnError>({ url: '/images/{name}', ...options });

/**
 * Get full-size image by name
 */
export const getImage = <ThrowOnError extends boolean = false>(options: Options<GetImageData, ThrowOnError>) => (options.client ?? client).get<GetImageResponses, GetImageErrors, ThrowOnError>({ url: '/images/{name}', ...options });

/**
 * Rename image or replace its file
 */
export const updateImage = <ThrowOnError extends boolean = false>(options: Options<UpdateImageData, ThrowOnError>) => (options.client ?? client).patch<UpdateImageResponses, UpdateImageErrors, ThrowOnError>({
    url: '/images/{name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get resized thumbnail of an image
 */
export const getImageThumbnail = <ThrowOnError extends boolean = false>(options: Options<GetImageThumbnailData, ThrowOnError>) => (options.client ?? client).get<GetImageThumbnailResponses, GetImageThumbnailErrors, ThrowOnError>({ url: '/images/{name}/thumbnail', ...options });
