// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateBackgroundData, GenerateBackgroundErrors, GenerateBackgroundResponses, GenerateBatchData, GenerateBatchErrors, GenerateBatchResponses, GenerateCharacterData, GenerateCharacterErrors, GenerateCharacterResponses, GetBatchStatusData, GetBatchStatusErrors, GetBatchStatusResponses, ListBatchesData, ListBatchesResponses, RegenerateCharacterPoseData, RegenerateCharacterPoseErrors, RegenerateCharacterPoseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Start batch image generation
 */
export const generateBatch = <ThrowOnError extends boolean = false>(options: Options<GenerateBatchData, ThrowOnError>) => (options.client ?? client).post<GenerateBatchResponses, GenerateBatchErrors, ThrowOnError>({
    url: '/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate character images in multiple poses
 *
 * Generates character images. First creates an idle pose, then uses it as reference to generate all other requested poses in parallel. All poses are rendered on transparent background.
 *
 */
export const generateCharacter = <ThrowOnError extends boolean = false>(options: Options<GenerateCharacterData, ThrowOnError>) => (options.client ?? client).post<GenerateCharacterResponses, GenerateCharacterErrors, ThrowOnError>({
    url: '/generate/character',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Regenerate a single character pose using an existing reference image
 *
 * Generates a single pose image using a provided reference image (e.g. the existing idle pose). Does not generate idle — uses the supplied referenceImageUrl as-is.
 *
 */
export const regenerateCharacterPose = <ThrowOnError extends boolean = false>(options: Options<RegenerateCharacterPoseData, ThrowOnError>) => (options.client ?? client).post<RegenerateCharacterPoseResponses, RegenerateCharacterPoseErrors, ThrowOnError>({
    url: '/generate/character/pose',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a background/environment scene
 *
 * Generates a single background image suitable as a visual novel backdrop. No characters are included — only environment and scenery.
 *
 */
export const generateBackground = <ThrowOnError extends boolean = false>(options: Options<GenerateBackgroundData, ThrowOnError>) => (options.client ?? client).post<GenerateBackgroundResponses, GenerateBackgroundErrors, ThrowOnError>({
    url: '/generate/background',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all batches with summary stats
 */
export const listBatches = <ThrowOnError extends boolean = false>(options?: Options<ListBatchesData, ThrowOnError>) => (options?.client ?? client).get<ListBatchesResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * Get detailed status of a batch
 */
export const getBatchStatus = <ThrowOnError extends boolean = false>(options: Options<GetBatchStatusData, ThrowOnError>) => (options.client ?? client).get<GetBatchStatusResponses, GetBatchStatusErrors, ThrowOnError>({ url: '/status/{batchId}', ...options });
