// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3100' | (string & {});
};

export type GenerateItem = {
    id: string;
    description: string;
    referenceImages?: Array<string>;
};

export type GenerateRequest = {
    masterPrompt?: string;
    negativePrompt?: string;
    items: Array<GenerateItem>;
};

export type GenerateResponse = {
    batchId: string;
    itemIds: Array<string>;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<string>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: number;
    pending: number;
    failed: number;
};

export type ErrorResponse = {
    error: string;
};

export type GenerateBatchData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/generate';
};

export type GenerateBatchErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type GenerateBatchError = GenerateBatchErrors[keyof GenerateBatchErrors];

export type GenerateBatchResponses = {
    /**
     * Batch accepted
     */
    200: GenerateResponse;
};

export type GenerateBatchResponse = GenerateBatchResponses[keyof GenerateBatchResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListBatchesResponses = {
    /**
     * List of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchStatusData = {
    body?: never;
    path: {
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: ErrorResponse;
};

export type GetBatchStatusError = GetBatchStatusErrors[keyof GetBatchStatusErrors];

export type GetBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetBatchStatusResponse = GetBatchStatusResponses[keyof GetBatchStatusResponses];
