// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3100' | (string & {});
};

export type GenerateItem = {
    id: string;
    description: string;
    referenceImages?: Array<string>;
};

export type GenerateRequest = {
    masterPrompt?: string;
    negativePrompt?: string;
    items: Array<GenerateItem>;
};

export type GenerateResponse = {
    batchId: string;
    itemIds: Array<string>;
};

export type CompletedItem = {
    id: string;
    /**
     * Generated image file name
     */
    file: string;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<CompletedItem>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: number;
    pending: number;
    failed: number;
};

export type CharacterGenerateRequest = {
    /**
     * Visual style/quality prompt applied to all generated images
     */
    masterPrompt: string;
    /**
     * Story context prompt (world, characters, plot) to inform character visual generation
     */
    storyMasterPrompt?: string;
    /**
     * Detailed description of the character appearance
     */
    characterDescription: string;
    /**
     * Optional list of poses/emotions to generate. Idle is always included automatically.
     */
    poses?: Array<string>;
};

export type RegeneratePoseRequest = {
    /**
     * Visual style/quality prompt applied to the generated image
     */
    masterPrompt: string;
    /**
     * Story context prompt (world, characters, plot) to inform character visual generation
     */
    storyMasterPrompt?: string;
    /**
     * Detailed description of the character appearance
     */
    characterDescription: string;
    /**
     * The pose/emotion to generate
     */
    pose: string;
    /**
     * URL of the existing idle pose image to use as style reference
     */
    referenceImageUrl: string;
};

export type BackgroundGenerateRequest = {
    /**
     * Global style/quality prompt applied to the generated image
     */
    masterPrompt: string;
    /**
     * Detailed description of the background/environment scene
     */
    sceneDescription: string;
};

export type ErrorResponse = {
    error: string;
};

export type GenerateBatchData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/generate';
};

export type GenerateBatchErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type GenerateBatchError = GenerateBatchErrors[keyof GenerateBatchErrors];

export type GenerateBatchResponses = {
    /**
     * Batch accepted
     */
    200: GenerateResponse;
};

export type GenerateBatchResponse = GenerateBatchResponses[keyof GenerateBatchResponses];

export type GenerateCharacterData = {
    body: CharacterGenerateRequest;
    path?: never;
    query?: never;
    url: '/generate/character';
};

export type GenerateCharacterErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type GenerateCharacterError = GenerateCharacterErrors[keyof GenerateCharacterErrors];

export type GenerateCharacterResponses = {
    /**
     * Character generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateCharacterResponse = GenerateCharacterResponses[keyof GenerateCharacterResponses];

export type RegenerateCharacterPoseData = {
    body: RegeneratePoseRequest;
    path?: never;
    query?: never;
    url: '/generate/character/pose';
};

export type RegenerateCharacterPoseErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type RegenerateCharacterPoseError = RegenerateCharacterPoseErrors[keyof RegenerateCharacterPoseErrors];

export type RegenerateCharacterPoseResponses = {
    /**
     * Pose regeneration batch accepted
     */
    200: GenerateResponse;
};

export type RegenerateCharacterPoseResponse = RegenerateCharacterPoseResponses[keyof RegenerateCharacterPoseResponses];

export type GenerateBackgroundData = {
    body: BackgroundGenerateRequest;
    path?: never;
    query?: never;
    url: '/generate/background';
};

export type GenerateBackgroundErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
};

export type GenerateBackgroundError = GenerateBackgroundErrors[keyof GenerateBackgroundErrors];

export type GenerateBackgroundResponses = {
    /**
     * Background generation batch accepted
     */
    200: GenerateResponse;
};

export type GenerateBackgroundResponse = GenerateBackgroundResponses[keyof GenerateBackgroundResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListBatchesResponses = {
    /**
     * List of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchStatusData = {
    body?: never;
    path: {
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: ErrorResponse;
};

export type GetBatchStatusError = GetBatchStatusErrors[keyof GetBatchStatusErrors];

export type GetBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetBatchStatusResponse = GetBatchStatusResponses[keyof GetBatchStatusResponses];
