// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GenerateMelodyData, GenerateMelodyErrors, GenerateMelodyResponses, GenerateSfxData, GenerateSfxErrors, GenerateSfxResponses, GenerateVariationData, GenerateVariationErrors, GenerateVariationResponses, GetAudioBatchStatusData, GetAudioBatchStatusErrors, GetAudioBatchStatusResponses, ListAudioBatchesData, ListAudioBatchesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate a base melody track
 */
export const generateMelody = <ThrowOnError extends boolean = false>(options: Options<GenerateMelodyData, ThrowOnError>) => (options.client ?? client).post<GenerateMelodyResponses, GenerateMelodyErrors, ThrowOnError>({
    url: '/generate/melody',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate a character-tinted variation of a base melody
 */
export const generateVariation = <ThrowOnError extends boolean = false>(options: Options<GenerateVariationData, ThrowOnError>) => (options.client ?? client).post<GenerateVariationResponses, GenerateVariationErrors, ThrowOnError>({
    url: '/generate/variation',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate emotional sound effects
 */
export const generateSfx = <ThrowOnError extends boolean = false>(options: Options<GenerateSfxData, ThrowOnError>) => (options.client ?? client).post<GenerateSfxResponses, GenerateSfxErrors, ThrowOnError>({
    url: '/generate/sfx',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get batch generation status
 */
export const getAudioBatchStatus = <ThrowOnError extends boolean = false>(options: Options<GetAudioBatchStatusData, ThrowOnError>) => (options.client ?? client).get<GetAudioBatchStatusResponses, GetAudioBatchStatusErrors, ThrowOnError>({ url: '/status/{batchId}', ...options });

/**
 * List all batches
 */
export const listAudioBatches = <ThrowOnError extends boolean = false>(options?: Options<ListAudioBatchesData, ThrowOnError>) => (options?.client ?? client).get<ListAudioBatchesResponses, unknown, ThrowOnError>({ url: '/status', ...options });
