// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3310' | (string & {});
};

export type GenerateMelodyRequest = {
    /**
     * Style description (genre, instruments, mood)
     */
    style: string;
    /**
     * Generate instrumental-only track
     */
    instrumental: boolean;
};

export type GenerateVariationRequest = {
    /**
     * Filename of base melody on audio_server
     */
    baseAudioName: string;
    /**
     * Style for the variation
     */
    toneStyle: string;
    /**
     * Type of variation
     */
    variationType: 'positive' | 'negative';
};

export type SfxItem = {
    /**
     * Unique ID for this SFX item
     */
    id: string;
    /**
     * Sound description prompt
     */
    prompt: string;
    /**
     * Whether sound should loop seamlessly
     */
    soundLoop?: boolean;
};

export type GenerateSfxRequest = {
    items: Array<SfxItem>;
};

export type BatchCreated = {
    batchId: string;
    itemIds: Array<string>;
};

export type CompletedItem = {
    id: string;
    file: string;
};

export type FailedItem = {
    id: string;
    error?: string;
};

export type BatchStatus = {
    batchId: string;
    createdAt: string;
    total: number;
    completed: Array<CompletedItem>;
    pending: Array<string>;
    failed: Array<FailedItem>;
    done: boolean;
};

export type BatchSummary = {
    batchId?: string;
    createdAt?: string;
    total?: number;
    completed?: number;
    pending?: number;
    failed?: number;
};

export type Error = {
    error: string;
};

export type GenerateMelodyData = {
    body: GenerateMelodyRequest;
    path?: never;
    query?: never;
    url: '/generate/melody';
};

export type GenerateMelodyErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type GenerateMelodyError = GenerateMelodyErrors[keyof GenerateMelodyErrors];

export type GenerateMelodyResponses = {
    /**
     * Batch created
     */
    200: BatchCreated;
};

export type GenerateMelodyResponse = GenerateMelodyResponses[keyof GenerateMelodyResponses];

export type GenerateVariationData = {
    body: GenerateVariationRequest;
    path?: never;
    query?: never;
    url: '/generate/variation';
};

export type GenerateVariationErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type GenerateVariationError = GenerateVariationErrors[keyof GenerateVariationErrors];

export type GenerateVariationResponses = {
    /**
     * Batch created
     */
    200: BatchCreated;
};

export type GenerateVariationResponse = GenerateVariationResponses[keyof GenerateVariationResponses];

export type GenerateSfxData = {
    body: GenerateSfxRequest;
    path?: never;
    query?: never;
    url: '/generate/sfx';
};

export type GenerateSfxErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type GenerateSfxError = GenerateSfxErrors[keyof GenerateSfxErrors];

export type GenerateSfxResponses = {
    /**
     * Batch created
     */
    200: BatchCreated;
};

export type GenerateSfxResponse = GenerateSfxResponses[keyof GenerateSfxResponses];

export type GetAudioBatchStatusData = {
    body?: never;
    path: {
        /**
         * Batch UUID
         */
        batchId: string;
    };
    query?: never;
    url: '/status/{batchId}';
};

export type GetAudioBatchStatusErrors = {
    /**
     * Batch not found
     */
    404: Error;
};

export type GetAudioBatchStatusError = GetAudioBatchStatusErrors[keyof GetAudioBatchStatusErrors];

export type GetAudioBatchStatusResponses = {
    /**
     * Batch status
     */
    200: BatchStatus;
};

export type GetAudioBatchStatusResponse = GetAudioBatchStatusResponses[keyof GetAudioBatchStatusResponses];

export type ListAudioBatchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type ListAudioBatchesResponses = {
    /**
     * Array of batch summaries
     */
    200: Array<BatchSummary>;
};

export type ListAudioBatchesResponse = ListAudioBatchesResponses[keyof ListAudioBatchesResponses];
